package com.casavida.backend.controllers;

import java.math.BigDecimal;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.casavida.backend.entity.*;
import com.casavida.backend.repository.*;
import com.casavida.backend.payload.request.LoginRequest;
import com.casavida.backend.payload.request.SignupRequest;
import com.casavida.backend.payload.response.JwtResponse;
import com.casavida.backend.payload.response.MessageResponse;
import org.springframework.transaction.annotation.Transactional;
import com.casavida.backend.repository.UserRepository;
import com.casavida.backend.security.jwt.JwtUtils;
import com.casavida.backend.security.services.UserDetailsImpl;

@RestController
@RequestMapping("/api/auth")
public class AuthController {
    @Autowired
    AuthenticationManager authenticationManager;

    @Autowired
    UserRepository userRepository;

    @Autowired
    RoleRepository roleRepository;

    @Autowired
    LoteRepository loteRepository;

    @Autowired
    FraccionamientoRepository fraccionamientoRepository;

    @Autowired
    PasswordEncoder encoder;

    @Autowired
    JwtUtils jwtUtils;

    @PostMapping("/signin")
    public ResponseEntity<?> authenticateUser(@Valid @RequestBody LoginRequest loginRequest) {
        Authentication authentication = authenticationManager.authenticate(
                new UsernamePasswordAuthenticationToken(loginRequest.getUsername(), loginRequest.getPassword()));

        SecurityContextHolder.getContext().setAuthentication(authentication);
        String jwt = jwtUtils.generateJwtToken(authentication);

        UserDetailsImpl userDetails = (UserDetailsImpl) authentication.getPrincipal();
        List<String> roles = userDetails.getAuthorities().stream()
                .map(item -> item.getAuthority())
                .collect(Collectors.toList());

        return ResponseEntity.ok(new JwtResponse(jwt,
                userDetails.getId(),
                userDetails.getUsername(),
                userDetails.getEmail(),
                roles));
    }

    @PostMapping("/signup")
    public ResponseEntity<?> registerUser(@Valid @RequestBody SignupRequest signUpRequest) {
        if (userRepository.existsByUsername(signUpRequest.getUsername())) {
            return ResponseEntity
                    .badRequest()
                    .body(new MessageResponse("Error: El nombre de usuario ya está en uso."));
        }

        if (userRepository.existsByEmail(signUpRequest.getEmail())) {
            return ResponseEntity
                    .badRequest()
                    .body(new MessageResponse("Error: El email ya está en uso."));
        }

        // Create new user's account
        User user = new User(null, // ID generated by DB
                signUpRequest.getUsername(),
                signUpRequest.getEmail(),
                encoder.encode(signUpRequest.getPassword()),
                new HashSet<>());

        Set<String> strRoles = signUpRequest.getRole();
        Set<Role> roles = new HashSet<>();

        if (strRoles == null) {
            Role userRole = roleRepository.findByName(ERole.ROLE_USER)
                    .orElseThrow(() -> new RuntimeException("Error: Role no encontrado."));
            roles.add(userRole);
        } else {
            strRoles.forEach(role -> {
                switch (role) {
                    case "admin":
                        Role adminRole = roleRepository.findByName(ERole.ROLE_ADMIN)
                                .orElseThrow(() -> new RuntimeException("Error: Role no encontrado."));
                        roles.add(adminRole);

                        break;
                    default:
                        Role userRole = roleRepository.findByName(ERole.ROLE_USER)
                                .orElseThrow(() -> new RuntimeException("Error: Role no encontrado."));
                        roles.add(userRole);
                }
            });
        }

        user.setRoles(roles);
        userRepository.save(user);

        return ResponseEntity.ok(new MessageResponse("Usuario registrado exitosamente!"));
    }

    // DEBUG ENDPOINT - REMOVE IN PRODUCTION

    @PostMapping("/debug/reset-admin")
    public ResponseEntity<?> debugResetAdmin(@RequestBody LoginRequest request) {
        if (!"admin-secret-key".equals(request.getUsername())) { // simple protection
            return ResponseEntity.badRequest().body(new MessageResponse("Unauthorized Debug Access"));
        }

        User user = userRepository.findByUsername("admin")
                .orElseThrow(() -> new RuntimeException("Error: Admin user not found."));

        user.setPassword(encoder.encode(request.getPassword()));
        userRepository.save(user);

        return ResponseEntity.ok(new MessageResponse("Admin password reset successfully via DEBUG endpoint. New hash: " + user.getPassword()));
    }

    // DEBUG ENDPOINT - CHECK PASSWORD
    @PostMapping("/debug/check")
    public ResponseEntity<?> debugCheckPassword(@RequestBody LoginRequest request) {
        if (!userRepository.existsByUsername(request.getUsername())) {
             return ResponseEntity.badRequest().body(new MessageResponse("User " + request.getUsername() + " does not exist"));
        }
        User user = userRepository.findByUsername(request.getUsername()).get();
        boolean matches = encoder.matches(request.getPassword(), user.getPassword());
        
        return ResponseEntity.ok(new MessageResponse("Password match for " + request.getUsername() + ": " + matches + ". Stored: " + user.getPassword() + ". Encoded input would be: " + encoder.encode(request.getPassword())));
    }
}
